name: Deploy
on: 
  push: 
    branches:
      - main
jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          ssh -t -i keyfile root@164.68.103.23 "cd ~/api-generator && git pull origin main && sudo bash ~/api-generator/deploy.sh $POSTGRES_PASSWORD"