name: Deploy
on: 
  push: 
    branches:
      - main
jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 700 keyfile
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          ssh -t -i keyfile $VPS_HOST "sudo bash ~/api-generator/deploy.sh "